# Generated by Django 4.1.6 on 2023-02-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = []
