# Generated by Django 4.1.6 on 2023-02-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20230207_1946"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Shops",
            new_name="Shop",
        ),
    ]
