# Generated by Django 4.1.6 on 2023-02-07 14:25

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_shops_shop"),
    ]

    operations = [
    ]
